// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudioSpremoBack.Models;

namespace StudioSpremoBack.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasMaxLength(128);

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("StudioSpremoBack.Models.Address", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<int>("Number");

                    b.Property<int>("PostalCode");

                    b.Property<string>("Street");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("StudioSpremoBack.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Contact");

                    b.Property<string>("ContactPerson");

                    b.Property<string>("Name");

                    b.Property<int>("PIB");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("StudioSpremoBack.Models.Courier", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AddressId");

                    b.Property<int>("CompanyId");

                    b.Property<string>("CourierName");

                    b.Property<DateTime>("DeliveryTime");

                    b.Property<int>("DeliveryTrackingNum");

                    b.Property<string>("RecipientName");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Couriers");
                });

            modelBuilder.Entity("StudioSpremoBack.Models.FilesFlexo", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FilePath");

                    b.Property<string>("JobId");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("FilesFlexo");
                });

            modelBuilder.Entity("StudioSpremoBack.Models.FilesOffset", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FilePath");

                    b.Property<string>("JobId");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("FilesOffset");
                });

            modelBuilder.Entity("StudioSpremoBack.Models.JobFlexo", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BrOtpremnice");

                    b.Property<bool>("CourierIncluded");

                    b.Property<bool>("FileShortening");

                    b.Property<bool>("IsDone");

                    b.Property<string>("JobName");

                    b.Property<int>("Liniature");

                    b.Property<string>("MaterialType");

                    b.Property<bool>("Montage");

                    b.Property<string>("Note");

                    b.Property<int>("ObimValjka");

                    b.Property<DateTime>("OrderedTime");

                    b.Property<bool>("OverprintBlack");

                    b.Property<string>("PolymerThicknessId");

                    b.Property<bool>("Prepress");

                    b.Property<string>("RadniNalog");

                    b.Property<double>("RollWidth");

                    b.Property<int>("SeparationSum");

                    b.Property<int>("Service");

                    b.Property<int>("ServiceId");

                    b.HasKey("Id");

                    b.HasIndex("PolymerThicknessId");

                    b.ToTable("JobsFlexo");
                });

            modelBuilder.Entity("StudioSpremoBack.Models.JobOffset", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BrOtpremnice");

                    b.Property<bool>("CourierIncluded");

                    b.Property<bool>("IsDone");

                    b.Property<string>("JobName");

                    b.Property<int>("Liniature");

                    b.Property<string>("Note");

                    b.Property<DateTime>("OrderedTime");

                    b.Property<bool>("OverprintBlack");

                    b.Property<string>("PlateDimensionId");

                    b.Property<int>("PlateSum");

                    b.Property<bool>("Prepress");

                    b.Property<string>("RadniNalog");

                    b.Property<int>("Service");

                    b.Property<int>("ServiceId");

                    b.HasKey("Id");

                    b.HasIndex("PlateDimensionId");

                    b.ToTable("JobsOffset");
                });

            modelBuilder.Entity("StudioSpremoBack.Models.PlateDimension", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Dimension");

                    b.HasKey("Id");

                    b.ToTable("PlateDimensions");
                });

            modelBuilder.Entity("StudioSpremoBack.Models.PolymerThickness", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Thickness");

                    b.HasKey("Id");

                    b.ToTable("PolymerThicknesses");
                });

            modelBuilder.Entity("StudioSpremoBack.Models.Client", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("AddressId");

                    b.Property<int>("CompanyId");

                    b.Property<string>("Name");

                    b.Property<string>("Surname");

                    b.HasIndex("AddressId");

                    b.HasIndex("CompanyId");

                    b.HasDiscriminator().HasValue("Client");
                });

            modelBuilder.Entity("StudioSpremoBack.Models.User", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("Name")
                        .HasColumnName("User_Name");

                    b.Property<int>("Role");

                    b.Property<int>("RoleId");

                    b.Property<string>("Surname")
                        .HasColumnName("User_Surname");

                    b.HasDiscriminator().HasValue("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("StudioSpremoBack.Models.Courier", b =>
                {
                    b.HasOne("StudioSpremoBack.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.HasOne("StudioSpremoBack.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("StudioSpremoBack.Models.FilesFlexo", b =>
                {
                    b.HasOne("StudioSpremoBack.Models.JobFlexo", "Job")
                        .WithMany("FilePaths")
                        .HasForeignKey("JobId");
                });

            modelBuilder.Entity("StudioSpremoBack.Models.FilesOffset", b =>
                {
                    b.HasOne("StudioSpremoBack.Models.JobOffset", "Job")
                        .WithMany("FilePaths")
                        .HasForeignKey("JobId");
                });

            modelBuilder.Entity("StudioSpremoBack.Models.JobFlexo", b =>
                {
                    b.HasOne("StudioSpremoBack.Models.PolymerThickness", "PolymerThickness")
                        .WithMany()
                        .HasForeignKey("PolymerThicknessId");
                });

            modelBuilder.Entity("StudioSpremoBack.Models.JobOffset", b =>
                {
                    b.HasOne("StudioSpremoBack.Models.PlateDimension", "PlateDimension")
                        .WithMany()
                        .HasForeignKey("PlateDimensionId");
                });

            modelBuilder.Entity("StudioSpremoBack.Models.Client", b =>
                {
                    b.HasOne("StudioSpremoBack.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.HasOne("StudioSpremoBack.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
